apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tabby
  namespace: tabby
spec:
  rules:
  - host: tabby.k8s.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tabby
            port:
              number: 8080